name = "ghl-nyfo-search"
account_id = "ae64efb1f95a08aa40f7103bf79178ea"
main = "search-contact.js"
compatibility_date = "2024-01-01"

[vars]
BASEROW_API_TOKEN = "oOcGyvGsuhv7ZfvcSo7nJLr5H30UA6Yv"
CONTACTS_TABLE_ID = "574979"
RELATIONSHIPS_TABLE_ID = "574977"
BASEROW_API_URL = "https://api.baserow.io/api/database"
