name = "ghl-nyfo"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

[vars]
BASEROW_API_TOKEN = "oOcGyvGsuhv7ZfvcSo7nJLr5H30UA6Yv"
CONTACTS_TABLE_ID = "574979"
RELATIONSHIPS_TABLE_ID = "574977"
BASEROW_API_URL = "https://api.baserow.io/api/database"
